#
#  Project configuration
#
ifeq ($(ON),)
	ON=1
endif
ifeq ($(OFF),)
	OFF=0
endif
DMOD_USE_STDLIB=ON
DMOD_USE_STDIO=ON
DMOD_USE_ASSERT=ON
DMOD_USE_PTHREAD=ON
DMOD_USE_FASTLZ=ON
DMOD_USE_MMAN=ON
DMOD_USE_ALIGNED_ALLOC=ON
DMOD_USE_ALIGNED_MALLOC_MOCK=OFF
DMOD_USE_GETENV=ON
DMOD_MAX_MODULES=30
DMOD_MAX_REQUIRED_MODULES=10
DMOD_SYSTEM_VERSION_MAJOR=0
DMOD_SYSTEM_VERSION_MINOR=1
DMOD_MODE=DMOD_SYSTEM
DMOD_BUILD_TESTS=OFF
DMOD_BUILD_EXAMPLES=OFF
DMOD_BUILD_TOOLS=OFF
DMOD_REPO_DIR=${DMOD_DMF_DIR}
DMOD_REPO_PATHS=${DMOD_DMF_DIR}${DMOD_ARRAY_SEP}${DMOD_DMFC_DIR}
DMOD_CPU_NAME=