name: CI Build

on:
  push:
    branches:
      - develop
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build project
        run: |
          cd build
          cmake --build .

      - name: Build summary
        run: |
          echo "Build completed successfully!"
          if [ -f build/libdmvfs.a ]; then
            ls -lh build/libdmvfs.a
          else
            echo "Warning: libdmvfs.a not found in expected location"
            find build -name "libdmvfs.a" -o -name "*.a" | head -10
          fi
